### ISSUE TITLE
Uncommitted code missing from repo files

### ISSUE THREAD

**Issue by benjaminmodayil** [jsfoundry/learnstatemachines-starter-files#3]
While on the **History States** video, I noticed that there were added lines in the video (screenshot below) that aren't found in the `Stoplight.js` files. Should this not be added in?

![image](https://user-images.githubusercontent.com/12306850/71905165-98837080-3135-11ea-87c9-16488511459f.png)

**Comment by jonbellah** [comment]
Sorry for the slow reply. This will be resolved in the forthcoming v2 of the course!

**Comment by benjaminmodayil** [comment]
@jonbellah Ooh. Any timeline on the v2 of the course/ notes about major differences in content?

**Comment by jonbellah** [comment]
v2 has been written, but I'm waiting on XState v5 to be released before I start recording.

It's a complete, ground-up rewrite of the course and associated app. No more `react-automata`, just uses XState directly (with React Hooks). Includes a new TypeScript module, coverage of the Actor model, and a whole bunch of other new stuff.

I'm expecting v2 to be roughly twice the size of v1.
